---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.my.domain
  resources:
  - schedulescalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.my.domain
  resources:
  - schedulescalers/finalizers
  verbs:
  - update
- apiGroups:
  - infra.my.domain
  resources:
  - schedulescalers/status
  verbs:
  - get
  - patch
  - update
